# Generated by Django 4.2.6 on 2023-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course_previews/', verbose_name='Preview Image Course')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lesson_previews/', verbose_name='Preview Image Lesson')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Video Link')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
